/*

 BOARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\Documents\Projects\Gameboy\gb_hello_world\res\tileset_extended_mini.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __board_h_INCLUDE
#define __board_h_INCLUDE

#define boardWidth 20
#define boardHeight 18
#define boardBank 0

extern const unsigned char board[];

#endif

/* End of BOARD.H */
